version: '3'

services:
  db:
    image: mysql:5.7.12
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: food_db
    ports:
      - 3306:3306

  app:
    build:
      context: ./api-server
    container_name: api-server
    environment:
      DB_RUL: mysql+mysqldb://root:1234@db:3306/my_database?charset=utf8m4
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always